"""add exercises table

Revision ID: 1022d9e48546
Revises: f99f325e3519
Create Date: 2026-08-29 10:10:07.659281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1022d9e48546'
down_revision: Union[str, Sequence[str], None] = 'f99f325e3519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', postgresql.ENUM('main', 'warmup', 'stretch', name='section', create_type=False), nullable=False),
    sa.Column('muscle_group', sa.String(length=60), nullable=True),
    sa.Column('movement_pattern', sa.Enum('compound', 'isolation', name='movementpattern'), nullable=True),
    sa.Column('equipment_needed', postgresql.ENUM('full_gym', 'home_basic', 'bodyweight_only', name='equipmentaccess', create_type=False), nullable=False),
    sa.Column('min_experience_level', postgresql.ENUM('beginner', 'intermediate', 'advanced', name='experiencelevel', create_type=False), nullable=False),
    sa.Column('suitable_goals', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('default_sets', sa.Integer(), nullable=False),
    sa.Column('default_reps_low', sa.Integer(), nullable=False),
    sa.Column('default_reps_high', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    # ### end Alembic commands ###
