"""add split_category to exercises

Revision ID: 4b726e388c08
Revises: 1022d9e48546
Create Date: 2026-08-29 10:19:38.405814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b726e388c08'
down_revision: Union[str, Sequence[str], None] = '1022d9e48546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column (unlike create_table) does NOT auto-create a new Postgres
    # enum type as part of the ALTER TABLE — has to be created explicitly first.
    split_category_enum = sa.Enum('push', 'pull', 'legs', 'core', name='splitcategory')
    split_category_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('exercises', sa.Column('split_category', split_category_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'split_category')
    sa.Enum(name='splitcategory').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
