"""add is_timed is_unilateral to exercises and duration_seconds to workout_logs

Revision ID: 52494c26f0f0
Revises: 579d61bbc6c9
Create Date: 2026-09-01 19:39:53.138196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52494c26f0f0'
down_revision: Union[str, Sequence[str], None] = '579d61bbc6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('is_timed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('exercises', sa.Column('is_unilateral', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workout_logs', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_logs', 'duration_seconds')
    op.drop_column('exercises', 'is_unilateral')
    op.drop_column('exercises', 'is_timed')
    # ### end Alembic commands ###
