"""add superset grouping to plan exercises

Revision ID: 579d61bbc6c9
Revises: e01ba8704940
Create Date: 2026-09-01 19:29:01.452942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579d61bbc6c9'
down_revision: Union[str, Sequence[str], None] = 'e01ba8704940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_exercises', sa.Column('superset_group_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_exercises', 'superset_group_id')
    # ### end Alembic commands ###
