"""add rpe and set_type to workout_logs

Revision ID: 7898fc6eb90a
Revises: b09648d1998c
Create Date: 2026-08-29 11:56:16.007520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7898fc6eb90a'
down_revision: Union[str, Sequence[str], None] = 'b09648d1998c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True))
    # add_column does NOT auto-create a new enum type the way create_table
    # does — create it explicitly first, same fix as the exercises table earlier.
    set_type_enum = sa.Enum('working', 'warmup', 'drop_set', 'amrap', 'failure', name='settype')
    set_type_enum.create(op.get_bind(), checkfirst=True)
    # server_default so existing rows (this is NOT NULL) get a sane value —
    # matches the Python-level default of SetType.working.
    op.add_column('workout_logs', sa.Column('set_type', set_type_enum, nullable=False, server_default='working'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_logs', 'set_type')
    op.drop_column('workout_logs', 'rpe')
    sa.Enum(name='settype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
