"""add progression engine fields

Revision ID: d645163a2d5f
Revises: 7898fc6eb90a
Create Date: 2026-09-01 18:20:07.922541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd645163a2d5f'
down_revision: Union[str, Sequence[str], None] = '7898fc6eb90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column does not auto-create a new enum type — create it explicitly
    # once, then reuse it (create_type=False) for the second column that
    # also uses it, same fix as previous migrations in this project.
    progression_rule_enum = sa.Enum('none', 'linear', 'greyskull_lp', 'double_progression', name='progressionrule')
    progression_rule_enum.create(op.get_bind(), checkfirst=True)
    progression_rule_enum_reuse = sa.Enum('none', 'linear', 'greyskull_lp', 'double_progression', name='progressionrule', create_type=False)

    op.add_column('plan_exercises', sa.Column('progression_rule', progression_rule_enum, nullable=True))
    op.add_column('plan_exercises', sa.Column('current_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('plan_exercises', sa.Column('current_reps_target', sa.Integer(), nullable=True))
    # server_default so existing rows (NOT NULL) get a sane starting value
    op.add_column('plan_exercises', sa.Column('consecutive_misses', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('plan_exercises', sa.Column('last_progression_note', sa.String(length=200), nullable=True))
    op.add_column('workout_plans', sa.Column('default_progression_rule', progression_rule_enum_reuse, nullable=False, server_default='linear'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plans', 'default_progression_rule')
    op.drop_column('plan_exercises', 'last_progression_note')
    op.drop_column('plan_exercises', 'consecutive_misses')
    op.drop_column('plan_exercises', 'current_reps_target')
    op.drop_column('plan_exercises', 'current_weight_kg')
    op.drop_column('plan_exercises', 'progression_rule')
    sa.Enum(name='progressionrule').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
