"""add body metric logs and goal weight

Revision ID: e01ba8704940
Revises: d645163a2d5f
Create Date: 2026-09-01 19:04:04.930101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01ba8704940'
down_revision: Union[str, Sequence[str], None] = 'd645163a2d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_metric_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_metric_logs_user_id'), 'body_metric_logs', ['user_id'], unique=False)
    op.add_column('user_profiles', sa.Column('goal_weight_kg', sa.Numeric(precision=5, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'goal_weight_kg')
    op.drop_index(op.f('ix_body_metric_logs_user_id'), table_name='body_metric_logs')
    op.drop_table('body_metric_logs')
    # ### end Alembic commands ###
