"""add user_profiles table

Revision ID: f99f325e3519
Revises: 904702b868db
Create Date: 2026-08-29 10:07:32.368372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99f325e3519'
down_revision: Union[str, Sequence[str], None] = '904702b868db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.Enum('strength', 'hypertrophy', 'fat_loss', 'endurance', 'general_fitness', name='goal'), nullable=False),
    sa.Column('experience_level', sa.Enum('beginner', 'intermediate', 'advanced', name='experiencelevel'), nullable=False),
    sa.Column('equipment_access', sa.Enum('full_gym', 'home_basic', 'bodyweight_only', name='equipmentaccess'), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('injuries_limitations', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
